defaultIndent: "  "
indentPreamble: 1
onlyOneBackUp: 1

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 0

verbatimEnvironments:
  verbatim: 1
  lstlisting: 1
  minted: 1
  tikzpicture: 1
