[packages]
fontspec     = "*"
unicode-math = "*"
lm-math      = "*"
mathtools    = "*"
physics2     = "*"
siunitx      = "*"
cleveref     = "*"
biblatex     = "*"
biber        = "*"
csquotes     = "*"
microtype    = "*"
booktabs     = "*"
hyperref     = "*"
hypcap       = "*"
selnolig     = "*"
todonotes    = "*"
pgf          = "*"
pgfplots     = "*"
chktex       = "*"
latexindent  = "*"
